openapi: 3.0.3
info:
  title: Factset Analytics Datastore About Holdings API
  description: Allow clients to fetch precalculated Analytics through predeterministic URLs.
  contact:
    name: FactSet Research Systems
    url: https://developer.factset.com/contact
    email: api@factset.com
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 1.0.0
servers:
- url: https://api.factset.com
  description: Production
- url: https://api-sandbox.factset.com
  description: Sandbox
security:
- basicAuth: []
tags:
- name: Holdings
paths:
  /factset-ownership/v1/fund-holdings:
    get:
      tags:
      - Holdings
      summary: Factset Get Underlying Holdings Information for a Requested Fund Identifer.
      operationId: getOwnershipHoldings
      description: 'Gets holdings information for list of fund identifiers. The service allows you to filter by the TopN holdings and Asset Type.

        '
      parameters:
      - $ref: '#/components/parameters/idFundHoldings'
      - $ref: '#/components/parameters/requestedDate'
      - $ref: '#/components/parameters/topn'
      - $ref: '#/components/parameters/assetType'
      - $ref: '#/components/parameters/currency'
      responses:
        '200':
          description: Fund Holdings Response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fundHoldingsResponse'
              examples:
                VTI-US Top 5 Equities Held as of 2019-12-31:
                  $ref: '#/components/examples/singleIdentifer'
                Top 5 Equity Holdings for VTI-USA, MABAX, and NZF as of 2019-12-31:
                  $ref: '#/components/examples/multipleIdentifiers'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '415':
          $ref: '#/components/responses/415'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    post:
      tags:
      - Holdings
      summary: Factset Get Holdings for a List of Funds.
      description: Gets Holding information for a long list of Fund objects.
      operationId: postOwnershipHoldings
      requestBody:
        required: true
        description: Requesting Underlying Holdings for a list of Fund Identifiers.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/fundHoldingsRequest'
            examples:
              Request to fetch the VTI-US Equity Fund-Holdings Details:
                $ref: '#/components/examples/singleIdentiferPostRequest'
              Request to fetch the Equity Fund-Holdings Details:
                $ref: '#/components/examples/MultipleIdentifiersPostRequest'
      responses:
        '200':
          description: Fund Holdings Response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fundHoldingsResponse'
              examples:
                Single identifier request for Top 5 Equity holdings as of 2019-12-31:
                  $ref: '#/components/examples/singleIdentifer'
                Multiple identifier request for Top 5 Equity holdings as of 2019-12-31:
                  $ref: '#/components/examples/multipleIdentifiers'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '415':
          $ref: '#/components/responses/415'
        '500':
          $ref: '#/components/responses/500'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /holdings-composite/{id}:
    get:
      operationId: readHoldingsComposite
      description: Read a holdings composite
      tags:
      - Holdings
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          example: 270c2fa8-9110-444b-9101-17e10132fe0a
        description: Unique identifier of the holdings composite to be read
        example: 270c2fa8-9110-444b-9101-17e10132fe0a
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/readHoldingsCompositeResponse'
        '400':
          $ref: '#/components/responses/BadRequestErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedErrorResponse'
        '403':
          $ref: '#/components/responses/ForbiddenErrorResponse'
        '404':
          $ref: '#/components/responses/NotFoundErrorResponse'
        '406':
          $ref: '#/components/responses/NotAcceptableErrorResponse'
        '415':
          $ref: '#/components/responses/UnsupportedMediaTypeErrorResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
        '501':
          $ref: '#/components/responses/NotImplementedErrorResponse'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /holdings/{id}:
    get:
      operationId: readHoldings
      description: Read a holdings
      tags:
      - Holdings
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          example: 270c2fa8-9110-444b-9101-17e10132fe0a
        description: Unique identifier of the holdings to be read
        example: 270c2fa8-9110-444b-9101-17e10132fe0a
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/readHoldingsResponse'
        '400':
          $ref: '#/components/responses/BadRequestErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedErrorResponse'
        '403':
          $ref: '#/components/responses/ForbiddenErrorResponse'
        '404':
          $ref: '#/components/responses/NotFoundErrorResponse'
        '406':
          $ref: '#/components/responses/NotAcceptableErrorResponse'
        '415':
          $ref: '#/components/responses/UnsupportedMediaTypeErrorResponse'
        '500':
          $ref: '#/components/responses/InternalServerErrorResponse'
        '501':
          $ref: '#/components/responses/NotImplementedErrorResponse'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    readHoldingsCompositeResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
              enum:
              - Account
              - AccountComposite
              - ExchangeRate
              - GlobalAccountProperties
              - Holdings
              - HoldingsComposite
              - PortfolioGroup
              - Returns
              - ReturnsComposite
              - SecurityMaster
              - TradeData
              - VendorReturnSeries
              nullable: false
              description: Metadata file type formatted for consistency with the REST api
            id:
              type: string
              nullable: false
              description: Unique identifier for this metadata file.
              example: f132625b-1506-4cc3-b2e8-2c75de39c79c
            display:
              type: string
              nullable: false
              description: The GUI path of this file, including the name and extension.
              example: SP50
            path:
              type: string
              nullable: false
              description: The GUI path to this object.
              example: 'Client:'
            name:
              type: string
              nullable: false
              description: Name of this file object including the extension.
              example: SP50
            description:
              type: string
              nullable: true
              description: User provided description of this file.
              example: Meaningful description of vendor returns
          nullable: true
          description: Read a metadata file by its id.
          example: example_value
      nullable: true
    idFundHoldings:
      description: List of Fund identifiers.
      type: array
      items:
        type: string
      minItems: 1
      maxItems: 10
      example:
      - FDIVX-US
    requestedDate:
      description: Date of holdings expressed in YYYY-MM-DD format.
      type: string
      example: '2019-09-30'
    fundHoldingsRequest:
      title: Holdings Request
      description: Holdings Request
      type: object
      properties:
        ids:
          $ref: '#/components/schemas/idFundHoldings'
        date:
          $ref: '#/components/schemas/requestedDate'
        topn:
          $ref: '#/components/schemas/topn'
        assetType:
          $ref: '#/components/schemas/assetType'
        currency:
          $ref: '#/components/schemas/currency'
      required:
      - ids
    assetType:
      description: Select type of assets returned, whereby EQ = Equity, FI = Fixed Income, and ALL = all asset types.
      type: string
      enum:
      - ALL
      - EQ
      - FI
      default: EQ
    readHoldingsResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
              enum:
              - Account
              - AccountComposite
              - ExchangeRate
              - GlobalAccountProperties
              - Holdings
              - HoldingsComposite
              - PortfolioGroup
              - Returns
              - ReturnsComposite
              - SecurityMaster
              - TradeData
              - VendorReturnSeries
              nullable: false
              description: Metadata file type formatted for consistency with the REST api
            id:
              type: string
              nullable: false
              description: Unique identifier for this metadata file.
              example: f132625b-1506-4cc3-b2e8-2c75de39c79c
            display:
              type: string
              nullable: false
              description: The GUI path of this file, including the name and extension.
              example: SP50
            path:
              type: string
              nullable: false
              description: The GUI path to this object.
              example: 'Client:'
            name:
              type: string
              nullable: false
              description: Name of this file object including the extension.
              example: SP50
            description:
              type: string
              nullable: true
              description: User provided description of this file.
              example: Meaningful description of vendor returns
          nullable: true
          description: Read a metadata file by its id.
          example: example_value
      nullable: true
    errorResponse:
      type: object
      description: error description
      title: Error Response
      properties:
        status:
          description: status
          type: string
          example: Bad Request
        timestamp:
          description: timestamp in YYYY-MM-DD HH:MM:SS.SSS
          type: string
          example: '2019-11-01 11:09:41.918'
          format: date-time
        path:
          description: The Endpoint path {package}/version/{endpoint}
          type: string
          example: /factset-ownership/v1/{end-point}
        message:
          description: The plain text error message
          type: string
          example: Validation Error
        subErrors:
          description: subErrors related to the error message. Null if not applicable.
          type: object
          properties:
            object:
              description: the operation ID
              type: string
            field:
              description: Parameter Field Name
              type: string
            message:
              description: Error message
              type: string
            rejectedValue:
              description: Rejected Values in an Array
              type: array
              items:
                type: string
          example: example_value
    Errors:
      type: object
      description: Information about one or more errors
      properties:
        errors:
          type: array
          description: List of errors
          items:
            type: object
            properties:
              id:
                type: string
                description: Unique identifier for this error instance.  Used to reference this error in logging.
                example: 270c2fa8-9110-444b-9101-17e10132fe0a
              code:
                type: string
                description: Error code for this error
                enum:
                - BadRequestError
                - UnauthorizedError
                - ForbiddenError
                - NotFoundError
                - NotAcceptableError
                - ConflictError
                - UnsupportedMediaTypeError
                - InternalServerError
                - NotImplementedError
              title:
                type: string
                description: HTTP reason phrase associcated with this error
                enum:
                - Bad Request
                - Unauthorized
                - Forbidden
                - Not Found
                - Not Acceptable
                - Conflict
                - Unsupported Media Type
                - Internal Server Error
                - Not Implemented
              detail:
                type: string
                description: Detailed description of the error that occurred
          example: []
      required:
      - errors
    topn:
      description: Limits number of holdings or holders displayed by the top *n* securities. Default is ALL, or use integer to limit number.
      type: string
      default: ALL
      example: 5
    currency:
      description: Currency code for adjusting prices. Default is Local. For a list of currency ISO codes, visit [Online Assistant Page 1470](https://oa.apps.factset.com/pages/1470).
      type: string
      example: USD
    fundHolding:
      title: Fund Holding
      description: fundHolding response object
      type: object
      properties:
        requestId:
          description: Fund Identifier that was used in the request.
          type: string
          example: VTI-US
        fsymId:
          description: FactSet Security Identifier of Fund. Identifies the security level id of the Fund requested (not-representing the underlying holding). Six alpha-numeric characters, excluding vowels, with an -S suffix (XXXXXX-S). All equity and fixed income securities that exist on FactSet are allocated a security-level permanent identifier.
          type: string
          example: K7ZVMR-S
          nullable: true
        date:
          description: 'Date of the reported holding in YYYY-MM-DD format. For more details, visit [Online Assistant Page #11262](https://oa.apps.factset.com/pages/11262).'
          type: string
          format: date
          example: '2018-06-30'
          nullable: true
        currency:
          description: 'Currency code. The service will default to the funds local currency. For a list of currency ISO codes, visit [Online Assistant Page #1470](https://oa.apps.factset.com/pages/1470).'
          type: string
          example: USD
          nullable: true
        adjHolding:
          description: 'Adjusted number of shares held. All positions and prices are adjusted for splits and name changes, but they are not adjusted for spinoffs or mergers. If a given company announces a split today, FactSet''s Ownership data will reflect that split either tomorrow or the day after, depending upon the time in which the FactSet Symbology team makes record of the change. For more details, visit [Online Assistant Page #11262](https://oa.apps.factset.com/pages/11262).'
          type: number
          format: double
          example: 60036157
          nullable: true
        adjMarketValue:
          description: 'Adjusted market values of shares held. Market Value. All positions and prices are adjusted for splits and name changes, but they are not adjusted for spinoffs or mergers. If a given company announces a split today, FactSet''s Ownership data will reflect that split either tomorrow or the day after, depending upon the time in which the FactSet Symbology team makes record of the change. For more details, visit [Online Assistant Page #11262](https://oa.apps.factset.com/pages/11262).'
          type: number
          format: double
          example: 120078159
          nullable: true
        weightClose:
          description: Closing weight of security in the fund for the requested asset type (percent).
          type: number
          format: double
          example: 1.6639
          nullable: true
        issueType:
          description: 'Issue type of held security. For more details, visit [Online Assistant Page #11262](https://oa.apps.factset.com/pages/11262).'
          type: string
          example: Equity
          nullable: true
        fsymSecurityId:
          description: Represents the security id for the underlying holding, not the parent holding. Six alpha-numeric characters, excluding vowels, with an -S suffix (XXXXXX-S). All equity and fixed income securities that exist on FactSet are allocated a security-level permanent identifier.
          type: string
          example: BHM9TN-S
          nullable: true
        fsymRegionalId:
          description: FactSet Regional Security identifier of the security held in the fund.
          type: string
          example: QLGSL2-R
          nullable: true
        securityName:
          description: Name of held security.
          type: string
          example: FACEBOOK INC  CL A
          nullable: true
        securityTicker:
          description: Ticker of held security.
          type: string
          example: FB-US
          nullable: true
    fundHoldingsResponse:
      title: Fund Holding Response
      type: object
      description: fundHolding response
      properties:
        data:
          description: Array of Fund holdings
          type: array
          items:
            $ref: '#/components/schemas/fundHolding'
          example: []
  examples:
    badRequestInvalidParameters:
      summary: Bad Request - Invalid Parameters
      description: This error message occurs when a request parameter is used in which is not recognized by the service. Please revise your request to include only the parameters listed in the specification. Typical causes are spelling mistakes and use of improper casing.
      value:
        status: Bad Request
        timestamp: '2020-08-03 12:02:47.804'
        path: /factset-ownership/v1/{end-point}
        message: 'Invalid Parameter (s): dated. Please modify your request to use parameters outlined in the specification for this endpoint.'
        subErrors: null
    badRequestDateFormat:
      summary: Bad Request - Date Format
      description: This bad request occurs when a request doesn't use the YYYY-MM-DD in the date parameters. To resolve, convert your date to YYYY-MM-DD.
      value:
        status: Bad Request
        timestamp: '2020-08-03 12:00:31.777'
        path: /factset-ownership/v1/{end-point}
        message: 'The date parameter(s) must be in the following date format: YYYY-MM-DD. '
        subErrors: null
    notWritable:
      summary: Internal Server Error - Not Writable
      description: This error may be returned when the server encounters an error writing the JSON response.
      value:
        status: Internal Server Error
        timestamp: '2019-11-05 09:48:29.18'
        path: /factset-ownership/v1/{endpoint}
        message: Error writing JSON output
        subErrors: null
    singleIdentiferPostRequest:
      summary: Request body to fetch the Top 5 Equity Holdings in VTI-US as of 2019 Year-End.
      description: The given post request body fetches the Top 5 Equity Holdings in the Vanguard Total Stock Index ETF as of 2019-12-31.
      value:
        ids:
        - VTI-US
        date: '2019-12-31'
        topn: 5
        assetType: EQ
    unsupportedMediaType:
      summary: Unsupported Media Type
      description: This bad request occurs when the media type passed in the request is not supported. Currently the APIs only support 'application/json'.
      value:
        status: Unsupported Media Type
        timestamp: '2019-11-05 09:42:27.237'
        path: /factset-ownership/v1/{endpoint}
        message: text/html media type is not supported. Supported media types are application/json
        subErrors: null
    generalException:
      summary: Internal Server Error - General Exception
      description: This is the most general error that can be returned to by the service. Please `Report Issue` to FactSet.
      value:
        status: Internal Server Error
        timestamp: '2019-11-01 10:36:01.944'
        path: /factset-ownership/v1/{endpoint}
        message: Unexpected error
        subErrors: null
    badRequestReadTimeout:
      summary: Bad Request - Read Timeout
      description: This error may be returned if it takes more than 29 seconds to hear back from the data fetch service.
      value:
        status: Bad Request
        timestamp: '2019-11-04 16:18:38.949'
        path: /factset-ownership/v1/{end-point}
        message: The request took too long. Try again with a smaller request.
        subErrors: null
    badRequestFutureDate:
      summary: Bad Request - Future Date
      description: This error message occurs when a future date is requested in the date parameters. Please revise your request to include dates as of today's current date or any prior historical date.
      value:
        status: Bad Request
        timestamp: '2020-08-03 12:02:06.097'
        path: /factset-ownership/v1/{end-point}
        message: 'The use of future dates for date parameter(s) is not applicable. Please revise your request to include dates up to today''s current date. '
        subErrors: null
    forbidden:
      summary: Forbidden
      description: The USERNAME-SERIAL attempted to request the endpoint is not authorized to access. The request was a legal request, but the server is refusing to respond. Please reach out to FactSet Account Team for assistance with authorization.
      value:
        status: Forbidden
        timestamp: '2020-06-12 16:08:51.731'
        path: /factset-ownership/v1/{endpoint}
        message: USERNAME-SERIAL does not have permission to use /factset-ownership/v1/{endpoint}
        subErrors: null
    singleIdentifer:
      summary: VTI-US Top 5 Equities Held as of 2019-12-31
      description: Underlying Fund Holdings for the Vanguard Total Stock Index ETF (VTI-US) filtered by the Top 5 Equities Held as of 2020-01-01.
      value:
        data:
        - requestId: VTI-US
          fsymId: K7ZVMR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 214894399
          adjMarketValue: 33888846722.3
          weightClose: 3.78696130582374
          issueType: Equity
          fsymSecurityId: DF3K29-S
          fsymRegionalId: P8R3C2-R
          securityName: MICROSOFT CORP  COM
          securityTicker: MSFT-US
        - requestId: VTI-US
          fsymId: K7ZVMR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 112647486
          adjMarketValue: 33078934263.9
          weightClose: 3.6964563923282
          issueType: Equity
          fsymSecurityId: R85KLC-S
          fsymRegionalId: MH33D6-R
          securityName: APPLE INC  COM
          securityTicker: AAPL-US
        - requestId: VTI-US
          fsymId: K7ZVMR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 11871374
          adjMarketValue: 21936399732.16
          weightClose: 2.45131673129814
          issueType: Equity
          fsymSecurityId: RMCVZ9-S
          fsymRegionalId: MCNYYL-R
          securityName: AMAZON COM INC  COM
          securityTicker: AMZN-US
        - requestId: VTI-US
          fsymId: K7ZVMR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 67790793
          adjMarketValue: 13914060263.25
          weightClose: 1.55484806714164
          issueType: Equity
          fsymSecurityId: BHM9TN-S
          fsymRegionalId: QLGSL2-R
          securityName: FACEBOOK INC  CL A
          securityTicker: FB-US
        - requestId: VTI-US
          fsymId: K7ZVMR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 53368129
          adjMarketValue: 12087881218.5
          weightClose: 1.35077888070268
          issueType: Equity
          fsymSecurityId: N138TY-S
          fsymRegionalId: DBNXVB-R
          securityName: BERKSHIRE HATHAWAY INC  CL B
          securityTicker: BRK.B-US
    unauthenticated:
      summary: User Authentication Failed
      description: This occurs when a user is not properly authenticated or recognized by the service. Please double check the USERNAME-SERIAL and API-Key used to request and ensure you are within the IP range specified for the Key. Report Issue under 401 error for help with troubleshooting.
      value:
        status: User Authentication Failed
        timestamp: '2019-10-31 16:08:07.945'
        path: /factset-ownership/v1/{endpoint}
        message: User Authentication Failed.
        subErrors: null
    MultipleIdentifiersPostRequest:
      summary: Request body to fetch the Equity Fund-Holdings Details
      description: The given post request body help to fetch the VTI-US,FDIVX-US top 5 Equity type fund-holding details till the date 2020-01-01.
      value:
        ids:
        - VTI-US
        - FDIVX-US
        date: '2019-12-31'
        topn: 5
        assetType: EQ
    badRequestMalformedJSON:
      summary: Bad Request - Malformed JSON Request
      description: This error may be returned when the request body is specified as JSON, but is not in proper JSON format.
      value:
        status: Bad Request
        timestamp: '2020-08-03 12:03:34.409'
        path: /factset-ownership/v1/{end-point}
        message: Malformed JSON Request
        subErrors: null
    multipleIdentifiers:
      summary: Top 5 Equity Holdings for VTI-US, MABAX, and NZF as of 2019-12-31
      description: The Top 5 Equity Holdings of VTI-US, MABAX, and NZF as of 2019-12-31.
      value:
        data:
        - requestId: VTI-USA
          fsymId: K7ZVMR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 214894399
          adjMarketValue: 33888846722.3
          weightClose: 3.78696130582374
          issueType: Equity
          fsymSecurityId: DF3K29-S
          fsymRegionalId: P8R3C2-R
          securityName: MICROSOFT CORP  COM
          securityTicker: MSFT-US
        - requestId: VTI-USA
          fsymId: K7ZVMR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 112647486
          adjMarketValue: 33078934263.9
          weightClose: 3.6964563923282
          issueType: Equity
          fsymSecurityId: R85KLC-S
          fsymRegionalId: MH33D6-R
          securityName: APPLE INC  COM
          securityTicker: AAPL-US
        - requestId: VTI-USA
          fsymId: K7ZVMR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 11871374
          adjMarketValue: 21936399732.16
          weightClose: 2.45131673129814
          issueType: Equity
          fsymSecurityId: RMCVZ9-S
          fsymRegionalId: MCNYYL-R
          securityName: AMAZON COM INC  COM
          securityTicker: AMZN-US
        - requestId: VTI-USA
          fsymId: K7ZVMR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 67790793
          adjMarketValue: 13914060263.25
          weightClose: 1.55484806714164
          issueType: Equity
          fsymSecurityId: BHM9TN-S
          fsymRegionalId: QLGSL2-R
          securityName: FACEBOOK INC  CL A
          securityTicker: FB-US
        - requestId: VTI-USA
          fsymId: K7ZVMR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 53368129
          adjMarketValue: 12087881218.5
          weightClose: 1.35077888070268
          issueType: Equity
          fsymSecurityId: N138TY-S
          fsymRegionalId: DBNXVB-R
          securityName: BERKSHIRE HATHAWAY INC  CL B
          securityTicker: BRK.B-US
        - requestId: MABAX
          fsymId: FNK7XP-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 625648
          adjMarketValue: 87215331.2
          weightClose: 4.44864700626477
          issueType: Equity
          fsymSecurityId: N5N6M6-S
          fsymRegionalId: NNKD2Y-R
          securityName: JPMORGAN CHASE & CO  COM
          securityTicker: JPM-US
        - requestId: MABAX
          fsymId: FNK7XP-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 1557832
          adjMarketValue: 83811361.6
          weightClose: 4.27501859756526
          issueType: Equity
          fsymSecurityId: G4G3T4-S
          fsymRegionalId: VWF970-R
          securityName: WELLS FARGO & CO  COM
          securityTicker: WFC-US
        - requestId: MABAX
          fsymId: FNK7XP-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 1283579
          adjMarketValue: 78811750.6
          weightClose: 4.02000030890412
          issueType: Equity
          fsymSecurityId: RGW4H5-S
          fsymRegionalId: FT8FQW-R
          securityName: VERIZON COMMUNICATIONS INC  COM
          securityTicker: VZ-US
        - requestId: MABAX
          fsymId: FNK7XP-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 865327
          adjMarketValue: 69130974.03
          weightClose: 3.52620687701667
          issueType: Equity
          fsymSecurityId: T6BMPP-S
          fsymRegionalId: RK3DL5-R
          securityName: CITIGROUP INC  COM
          securityTicker: C-US
        - requestId: MABAX
          fsymId: FNK7XP-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 1588034
          adjMarketValue: 62219172.12
          weightClose: 3.1736522693376
          issueType: Equity
          fsymSecurityId: JDQZCY-S
          fsymRegionalId: VK7M4R-R
          securityName: PFIZER INC  COM
          securityTicker: PFE-US
        - requestId: NZF
          fsymId: WHX5ZR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 43420
          adjMarketValue: 689075.4
          weightClose: 35.5351354424324
          issueType: Closed-End Mutual Fund
          fsymSecurityId: DXZPQ5-S
          fsymRegionalId: KHSMRN-R
          securityName: PIMCO MUNICIPAL INCOME FD II  COM
          securityTicker: PML-US
        - requestId: NZF
          fsymId: WHX5ZR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 43020
          adjMarketValue: 552807
          weightClose: 28.5078695575618
          issueType: Closed-End Mutual Fund
          fsymSecurityId: L8RGHS-S
          fsymRegionalId: HJLD94-R
          securityName: INVESCO TRUST INVMT GRADE MUNICIPALS
          securityTicker: VGM-US
        - requestId: NZF
          fsymId: WHX5ZR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 30000
          adjMarketValue: 370800
          weightClose: 19.1218961263948
          issueType: Closed-End Mutual Fund
          fsymSecurityId: TG4L4R-S
          fsymRegionalId: W13K8B-R
          securityName: INVESCO MUNICIPAL OPPORTUNITY TRUST
          securityTicker: VMO-US
        - requestId: NZF
          fsymId: WHX5ZR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 26880
          adjMarketValue: 228748.8
          weightClose: 11.796415298375
          issueType: Closed-End Mutual Fund
          fsymSecurityId: J997TS-S
          fsymRegionalId: NK4SPV-R
          securityName: BNY MELLON STRATEGIC MUNICIPALS  COM
          securityTicker: LEO-US
        - requestId: NZF
          fsymId: WHX5ZR-S
          date: '2019-12-31'
          currency: USD
          adjHolding: 6266
          adjMarketValue: 106146.04
          weightClose: 5.47387689079867
          issueType: Closed-End Mutual Fund
          fsymSecurityId: V3L197-S
          fsymRegionalId: Q9MW50-R
          securityName: BLACKROCK MUNIHOLDINGS FUND INC
          securityTicker: MHD-US
    badRequestRequiredParameter:
      summary: Bad Request - Required Parameter Missing
      description: This error message occurs when the request does not include the required parameters. Required parameters are indicated with a red asterisks symbol in the specification file.
      value:
        status: Bad Request
        timestamp: '2020-08-03 12:01:06.553'
        path: /factset-ownership/v1/{end-point}
        message: The parameter 'ids' is required and may not be empty.
        subErrors: null
  responses:
    '401':
      description: Unauthenticated USERNAME-SERIAL. Ensure you are logged in and have successfully generated an API KEY for the IP range you are connecting from. For more help, select the **Report Issue** in the top right corner of this Developer Portal specification card and choose Connectivity 401 or 403 Responses.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
          examples:
            Bad Request - Date Format:
              $ref: '#/components/examples/unauthenticated'
    BadRequestErrorResponse:
      description: The server cannot or will not process the request due to an apparent client error (e.g., malformed request syntax, size too large, invalid request message framing, or deceptive request routing).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    '415':
      description: Unsupported Media Type. This error may be returned when the caller sends a resource in a format that is not accepted by the server. This can be fixed by ensuring that Content-Type header is set to the correct value. In this instance, "application/json" would be the appropriate value.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
          examples:
            Bad Request - Date Format:
              $ref: '#/components/examples/unsupportedMediaType'
    '403':
      description: The USERNAME-SERIAL attempted to request the endpoint is not authorized to access. The request was a legal request, but the server is refusing to respond. Please reach out to FactSet Account Team for assistance with authorization.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
          examples:
            Bad Request - Date Format:
              $ref: '#/components/examples/forbidden'
    ForbiddenErrorResponse:
      description: The request contained valid data and was understood by the server, but the server is refusing action. This may be due to the user not having the necessary permissions for a resource or needing an account of some sort, or attempting a prohibited action.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    NotFoundErrorResponse:
      description: The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    UnauthorizedErrorResponse:
      description: Similar to 403 Forbidden, but specifically for use when authentication is required and has failed or has not yet been provided.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    UnsupportedMediaTypeErrorResponse:
      description: The request entity has a media type which the server or resource does not support.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    NotImplementedErrorResponse:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    NotAcceptableErrorResponse:
      description: The requested resource is capable of generating only content not acceptable according to the Accept headers sent in the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    '500':
      description: Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
          examples:
            Internal Server Error - Not Writable:
              $ref: '#/components/examples/notWritable'
            Internal Server Error - General Exception:
              $ref: '#/components/examples/generalException'
    InternalServerErrorResponse:
      description: ''
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    '400':
      description: Bad Request. This can occur for several reasons. Please review the "message" for more details.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
          examples:
            Bad Request - Date Format:
              $ref: '#/components/examples/badRequestDateFormat'
            Bad Request - Missing Required Parameter:
              $ref: '#/components/examples/badRequestRequiredParameter'
            Bad Request - Future Date:
              $ref: '#/components/examples/badRequestFutureDate'
            Bad Request - Invalid Parameter:
              $ref: '#/components/examples/badRequestInvalidParameters'
            Bad Request - Malformed JSON:
              $ref: '#/components/examples/badRequestMalformedJSON'
            Bad Request - Read Timeout:
              $ref: '#/components/examples/badRequestReadTimeout'
  parameters:
    assetType:
      name: assetType
      schema:
        type: string
        default: EQ
        enum:
        - ALL
        - EQ
        - FI
      description: "Filter holdings by the following major asset classes -\n  * **EQ**  = Equity\n  * **FI** = Fixed Income\n  * **ALL** = ALL\n"
      in: query
      required: false
      example: EQ
    idFundHoldings:
      name: ids
      description: List of requested fund identifiers. <p>***ids limit** =  10 per request*</p>
      in: query
      schema:
        type: array
        items:
          type: string
        minItems: 1
        maxItems: 10
      required: true
      explode: false
      examples:
        singleIdentifer:
          summary: One identifier to know the fund holding details
          value:
          - VTI-USA
        multipleIdentifers:
          summary: Multiple identifiers to know the fund holding details
          value:
          - VTI-USA
          - MABAX
          - NZF
    requestedDate:
      name: date
      in: query
      schema:
        type: string
      required: false
      description: Date of holdings expressed in YYYY-MM-DD format. The fund-holdings endpoint will default to latest month-end close.
      example: '2019-12-31'
    currency:
      name: currency
      in: query
      schema:
        type: string
      description: Currency code for adjusting prices. Default is Local. For a list of currency ISO codes, visit [Online Assistant Page 1470](https://oa.apps.factset.com/pages/1470).
      example: USD
    topn:
      name: topn
      description: Limits number of holdings or holders displayed by the top *n* securities based on positions Market Value. Default is ALL, otherwise use number to limit number.
      in: query
      required: false
      schema:
        type: string
        default: ALL
      example: 5
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
externalDocs:
  url: https://developer.factset.com/api-catalog/analytics-datastore-api
  description: API Documentation
