openapi: 3.2.0
info:
  version: 1.0.0
  title: FactSet Vermilion User API
  contact:
    name: FactSet Research Systems
    email: api@factset.com
    url: https://developer.factset.com/contact
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  description: '

    The Vermilion API, enables users to programmatically access FactSet''s

    Vermilion Reporting Suite (VRS) and seamlessly integrate into customer''s

    3rd party applications. The API is referred to as two key product

    initiatives, the REST API and the SCIM API.'
security:
- FactSetApiKey: []
- FactSetOAuth2: []
tags:
- name: User
paths:
  /scim/v2/Users/{userId}:
    get:
      operationId: getUserById
      tags:
      - User
      summary: Factset Retrieves a Vrs User
      description: Retrieves a VRS user based on their ID
      parameters:
      - in: path
        name: userId
        description: The ID of the user
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/ScimUser'
          headers:
            Location:
              schema:
                type: string
              description: A callback URL to the user, for example https://example.com/VRSAPI/scim/v2/Users/1
        '403':
          description: Forbidden, user does not have permission to view users
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/ScimError'
              example:
                schemas:
                - urn:ietf:params:scim:api:messages:2.0:Error
                detail: User does not have permission to view users
                status: '403'
        '404':
          description: Not Found
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/ScimError'
              example:
                schemas:
                - urn:ietf:params:scim:api:messages:2.0:Error
                detail: Resource 1 not found
                status: '404'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      operationId: deleteUserById
      tags:
      - User
      summary: Factset Deletes a Vrs User
      description: Deletes a VRS user (this marks them as 'Deleted' in the database)
      parameters:
      - in: path
        name: userId
        description: The ID of the user
        schema:
          type: string
        required: true
      responses:
        '204':
          description: No Content
        '403':
          description: Forbidden, user does not have permission to delete users
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/ScimError'
              example:
                schemas:
                - urn:ietf:params:scim:api:messages:2.0:Error
                detail: User does not have permission to delete users
                status: '403'
        '404':
          description: Not Found
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/ScimError'
              example:
                schemas:
                - urn:ietf:params:scim:api:messages:2.0:Error
                detail: Resource 1 not found
                status: '404'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    patch:
      operationId: patchUserById
      tags:
      - User
      summary: Factset Add or Remove Vrs User Attributes
      description: Adds or removes VRS user attributes based on the JSON properties
      parameters:
      - in: path
        name: userId
        description: The ID of the user
        schema:
          type: string
        required: true
      requestBody:
        required: true
        content:
          application/scim+json:
            schema:
              $ref: '#/components/schemas/ScimUserPatchRequestBody'
            example:
              schemas:
              - urn:ietf:params:scim:api:messages:2.0:PatchOp
              Operations:
              - op: replace
                path: name.formatted
                value: vrstestuser1
      responses:
        '200':
          description: Successfully updated user
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/ScimUser'
          headers:
            Location:
              schema:
                type: string
              description: A callback URL to the updated user, for example https://example.com/VRSAPI/scim/v2/Users/1
        '403':
          description: Forbidden, user does not have permission to update users
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/ScimError'
              example:
                schemas:
                - urn:ietf:params:scim:api:messages:2.0:Error
                detail: User does not have permission to update users
                status: '403'
        '404':
          description: Not Found
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/ScimError'
              example:
                schemas:
                - urn:ietf:params:scim:api:messages:2.0:Error
                detail: Resource 1 not found
                status: '404'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    put:
      operationId: updateUserById
      tags:
      - User
      summary: Factset Updates a Vrs User
      description: Updates (replaces) a VRS user with the properties in the JSON
      parameters:
      - in: path
        name: userId
        description: The ID of the user
        schema:
          type: string
        required: true
      requestBody:
        required: true
        content:
          application/scim+json:
            schema:
              $ref: '#/components/schemas/ScimUser'
      responses:
        '200':
          description: Successfully updated user
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/ScimUser'
          headers:
            Location:
              schema:
                type: string
              description: A callback URL to the updated user, for example https://example.com/VRSAPI/scim/v2/Users/1
        '403':
          description: Forbidden, user does not have permission to update users
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/ScimError'
              example:
                schemas:
                - urn:ietf:params:scim:api:messages:2.0:Error
                detail: User does not have permission to update users
                status: '403'
        '404':
          description: Not Found
          content:
            application/scim+json:
              schema:
                $ref: '#/components/schemas/ScimError'
              example:
                schemas:
                - urn:ietf:params:scim:api:messages:2.0:Error
                detail: Resource 1 not found
                status: '404'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    ScimUserGroup:
      type: object
      properties:
        value:
          type: string
          example: example_value
        $ref:
          type: string
          description: A callback link which can be used to get the information of the user
          example: example_value
        type:
          type: string
          example: example_value
        display:
          type: string
          description: Name of the group
          example: example_value
    ScimEmail:
      type: object
      properties:
        value:
          type: string
          example: example_value
        type:
          type: string
          example: example_value
        primary:
          type: boolean
          example: true
    ScimPhoto:
      type: object
      properties:
        value:
          type: string
          example: example_value
        type:
          type: string
          example: example_value
        primary:
          type: boolean
          example: true
    Tenancy:
      type: object
      properties:
        value:
          type: string
          example: example_value
    ScimError:
      type: object
      properties:
        schemas:
          type: array
          items:
            type: string
          example: []
        detail:
          type: string
          example: example_value
        status:
          type: string
          example: example_value
    ScimMeta:
      type: object
      properties:
        resourceType:
          type: string
          example: example_value
        created:
          type: string
          example: example_value
        lastModified:
          type: string
          example: example_value
        location:
          type: string
          example: example_value
    ScimPhone:
      type: object
      properties:
        value:
          type: string
          example: example_value
        type:
          type: string
          example: example_value
        primary:
          type: boolean
          example: true
    ScimUser:
      type: object
      properties:
        schemas:
          type: array
          items:
            type: string
          example: []
        id:
          type: integer
          example: abc123
        userName:
          type: string
          example: example_value
        name:
          type: object
          properties:
            formatted:
              type: string
          example: Example Title
        userType:
          type: string
          example: example_value
        active:
          type: boolean
          example: true
        authenticatedUserName:
          type: string
          example: example_value
        tenant:
          type: string
          example: example_value
        phoneNumbers:
          type: array
          items:
            $ref: '#/components/schemas/ScimPhone'
          example: []
        emails:
          type: array
          items:
            $ref: '#/components/schemas/ScimEmail'
          example: user@example.com
        photos:
          type: array
          items:
            $ref: '#/components/schemas/ScimPhoto'
          example: []
        tenancies:
          type: array
          items:
            $ref: '#/components/schemas/Tenancy'
          example: []
        groups:
          type: array
          items:
            $ref: '#/components/schemas/ScimUserGroup'
          example: []
        domainCode:
          type: string
          example: example_value
        isAdministrator:
          type: boolean
          example: true
        meta:
          $ref: '#/components/schemas/ScimMeta'
    ScimUserPatchRequestBody:
      type: object
      properties:
        schemas:
          type: array
          items:
            type: string
          example: []
        Operations:
          type: array
          items:
            properties:
              op:
                type: string
              path:
                type: string
              value:
                type: string
          example: []
  securitySchemes:
    FactSetOAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.factset.com/as/token.oauth2
          scopes: {}
    FactSetApiKey:
      type: http
      scheme: basic
externalDocs:
  description: API Documentation
  url: https://developer.factset.com/api-catalog/vermilion-api
